# PostgreSQL Configuration for Rails
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "MGKishore_2223") %>
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>

development:
  adapter: postgresql
  encoding: unicode
  database: blog_app_development
  username: postgres
  password: MGKishore_2223
  host: localhost
  port: 5432


test:
  <<: *default
  database: blog_app_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

  cache:
    <<: *default
    url: <%= ENV.fetch("DATABASE_CACHE_URL", ENV["DATABASE_URL"]) %>
    migrations_paths: db/cache_migrate

  queue:
    <<: *default
    url: <%= ENV.fetch("DATABASE_QUEUE_URL", ENV["DATABASE_URL"]) %>
    migrations_paths: db/queue_migrate

  cable:
    <<: *default
    url: <%= ENV.fetch("DATABASE_CABLE_URL", ENV["DATABASE_URL"]) %>
    migrations_paths: db/cable_migrate
