# PostgreSQL Configuration for Rails

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: blog_app_development
  username: postgres
  password: MGKishore_2223
  host: localhost

test:
  <<: *default
  database: blog_app_test
  username: postgres
  password: MGKishore_2223
  host: localhost

production: &primary_production
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  username: <%= ENV["BLOG_APP_PRODUCTION_USER"] %>
  password: <%= ENV["BLOG_APP_DATABASE_PASSWORD"] %>
  host: <%= ENV["BLOG_APP_PRODUCTION_HOST"] %>

cache:
  <<: *default
  url: <%= ENV.fetch("DATABASE_CACHE_URL", ENV["DATABASE_URL"]) %>
  migrations_paths: db/cache_migrate

queue:
  <<: *default
  url: <%= ENV.fetch("DATABASE_QUEUE_URL", ENV["DATABASE_URL"]) %>
  migrations_paths: db/queue_migrate

cable:
  <<: *primary_production
  database: <%= ENV.fetch("BLOG_APP_PRODUCTION_CABLE_DB", "blog_app_production_cable") %>
  migrations_paths: db/cable_migrate
